---
- name: Install Ubuntu packages
  hosts: ubuntu_user
  become: yes
  tasks:
    - name: Update Ubuntu package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Copy Ubuntu packages to target server
      ansible.builtin.copy:
        src: /home/sarvind/ansible/Ubuntu_packages/
        dest: /tmp/Ubuntu_packages/
        remote_src: no
        mode: '0755'

    - name: Make ubuntu.sh script executable
      ansible.builtin.file:
        path: /tmp/Ubuntu_packages/ubuntu.sh
        mode: '0755'

    - name: Run ubuntu.sh script
      ansible.builtin.shell: |
        ./ubuntu.sh
      args:
        chdir: /tmp/Ubuntu_packages

    - name: Copy additional script to target server
      ansible.builtin.copy:
        src: /home/sarvind/git/basic_bash/myscript.sh
        dest: /tmp/Ubuntu_packages/myscript.sh
        remote_src: no
        mode: '0755'
