---
- name: Install Ubuntu packages
  hosts: ubuntu_user
  become: yes
  tasks:
    - name: Copy package files to target server
      community.general.copy:
        src: /home/sarvind/ansible/Ubuntu_packages/
        dest: /tmp/Ubuntu_packages/

    - name: Make the script executable
      ansible.builtin.file:
        path: /tmp/Ubuntu_packages/ubuntu.sh
        mode: '0755'

    - name: Run ubuntu.sh script
      ansible.builtin.shell: |
        ./ubuntu.sh
      args:
        chdir: /tmp/Ubuntu_packages
