---
- name: Install Ubuntu packages
  hosts: ubuntu_user
  become: yes
  tasks:
    - name: Copy package files to target server
      ansible.builtin.rsync:
        src: /home/sarvind/ansible/Ubuntu_packages/
        dest: /tmp/Ubuntu_packages/
        archive: true
        compress: true
        delete: false

    - name: Run ubuntu.sh script
      ansible.builtin.shell: |
        cd /tmp/Ubuntu_packages
        ./ubuntu.sh
      args:
        chdir: /tmp/Ubuntu_packages
