---
- name: Install Ubuntu packages
  hosts: ubuntu_user
  become: yes
  tasks:
    - name: update ubutu
      ansible.builtin.apt:
         update_cache: yes
    - name: Copy package files to target server
      ansible.builtin.copy:
        src: /home/sarvind/ansible/Ubuntu_packages/
        dest: /tmp/Ubuntu_packages/
        recurse: yes  # Make sure subdirectories and files are copied

    - name: Make the script executable
      ansible.builtin.file:
        path: /tmp/Ubuntu_packages/ubuntu.sh
        mode: '0755'

    - name: Run ubuntu.sh script
      ansible.builtin.shell: |
        ./ubuntu.sh
      args:
        chdir: /tmp/Ubuntu_packages
    - name: Copy Script files to target server
      ansible.builtin.copy:
        src: /home/sarvind/git/basic_bash/myscript.sh
        dest: /tmp/Ubuntu_packages/
        recurse: yes  # Make sure subdirectories and files are copied

    - name: Make the script executable
      ansible.builtin.file:
        path: /tmp/Ubuntu_packages/myscript.sh
        mode: '0755'

